// actionTypes

export const LOAD_POP_MOVIES = 'LOAD_POP_MOVIES';
export const LOAD_RECENT_MOVIES = 'LOAD_RECENT_MOVIES';
export const LOAD_TOP_MOVIES = 'LOAD_TOP_MOVIES';
export const LOAD_UPCOMING_MOVIES = 'LOAD_UPCOMING_MOVIES';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';

export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_SUMMARY = 'FETCH_MOVIE_SUMMARY';
export const FETCH_CAST_NAMES = 'FETCH_CAST_NAME';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const TURN_OFF_MODAL = 'TURN_OFF_MODAL';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_LIST = 'FETCH_LIST';
export const MOVIE_SAVED = 'MOVIE_SAVED';
export const MOVIE_UNSAVED = 'MOVIE_UNSAVED';
